### PR TITLE
feat: added cart management 

### PR DESCRIPTION
**Pull request by AtulHande03a**
Added cart item and cart summary components
Added context providers for cart page
Added logics for handling cart functionality
Updated stylesheet for cart components

### CODE REVIEW

**Review by sonishreyas — APPROVED** [review]
Code looks good. Really like the folder structure

**Review by SanjayJatti — APPROVED** [review]
- It will be good if created constants for reducer 
- File structure is very nice
- Code is clean

**Review by vaibhav18matere — APPROVED** [review]
Looks good. Clean code , you can go for merge.

**Review by vaibhav-mahalle — APPROVED** [review]
Liked the way you have broken the commits in a clear and concise manner. Everything else looks good,you can go ahead and merge

**Pull request merged**
